-- 1. Ensure all Lines exist
INSERT INTO lines (id, name, mode, color) VALUES
('kajang-line', 'MRT Kajang Line', 'MRT', '#00793e'),
('putrajaya-line', 'MRT Putrajaya Line', 'MRT', '#ffcd00'),
('kelana-jaya-line', 'LRT Kelana Jaya Line', 'LRT', '#e0004d'),
('ampang-line', 'LRT Ampang Line', 'LRT', '#ff8200'),
('sri-petaling-line', 'LRT Sri Petaling Line', 'LRT', '#6e0e28'),
('kl-monorail', 'KL Monorail', 'MONORAIL', '#78be20')
ON CONFLICT (id) DO NOTHING;

-- 2. Insert/Update All Stations
-- We use ON CONFLICT to update existing ones or insert new ones.

INSERT INTO stations (id, name, line_id, sequence) VALUES
-- MRT KAJANG LINE (SBK)
('sbk01', 'Kwasa Damansara', 'kajang-line', 1),
('sbk02', 'Sungai Buloh', 'kajang-line', 2),
('sbk03', 'Kampung Selamat', 'kajang-line', 3),
('sbk04', 'Kwasa Sentral', 'kajang-line', 4),
('sbk05', 'Kota Damansara', 'kajang-line', 5),
('sbk06', 'Surian', 'kajang-line', 6),
('sbk07', 'Mutiara Damansara', 'kajang-line', 7),
('sbk08', 'Bandar Utama', 'kajang-line', 8),
('sbk09', 'Taman Tun Dr Ismail', 'kajang-line', 9),
('sbk10', 'Phileo Damansara', 'kajang-line', 10),
('sbk12', 'Pusat Bandar Damansara', 'kajang-line', 12),
('sbk13', 'Semantan', 'kajang-line', 13),
('sbk14', 'Muzium Negara', 'kajang-line', 14),
('sbk15', 'Pasar Seni', 'kajang-line', 15),
('sbk16', 'Merdeka', 'kajang-line', 16),
('sbk17', 'Bukit Bintang', 'kajang-line', 17),
('sbk18', 'Tun Razak Exchange', 'kajang-line', 18),
('sbk19', 'Cochrane', 'kajang-line', 19),
('sbk20', 'Maluri', 'kajang-line', 20),
('sbk21', 'Taman Midah', 'kajang-line', 21),
('sbk22', 'Taman Mutiara', 'kajang-line', 22),
('sbk23', 'Taman Connaught', 'kajang-line', 23),
('sbk24', 'Taman Suntex', 'kajang-line', 24),
('sbk25', 'Sri Raya', 'kajang-line', 25),
('sbk26', 'Bandar Tun Hussein Onn', 'kajang-line', 26),
('sbk27', 'Batu 11 Cheras', 'kajang-line', 27),
('sbk28', 'Bukit Dukung', 'kajang-line', 28),
('sbk29', 'Sungai Jernih', 'kajang-line', 29),
('sbk30', 'Stadium Kajang', 'kajang-line', 30),
('sbk31', 'Kajang', 'kajang-line', 31),

-- MRT PUTRAJAYA LINE (PY)
('py01', 'Kwasa Damansara', 'putrajaya-line', 1),
('py03', 'Sungai Buloh', 'putrajaya-line', 3),
('py04', 'Damansara Damai', 'putrajaya-line', 4),
('py05', 'Sri Damansara Barat', 'putrajaya-line', 5),
('py06', 'Sri Damansara Sentral', 'putrajaya-line', 6),
('py07', 'Sri Damansara Timur', 'putrajaya-line', 7),
('py08', 'Metro Prima', 'putrajaya-line', 8),
('py09', 'Kepong Baru', 'putrajaya-line', 9),
('py10', 'Jinjang', 'putrajaya-line', 10),
('py11', 'Sri Delima', 'putrajaya-line', 11),
('py12', 'Kampung Batu', 'putrajaya-line', 12),
('py13', 'Kentonmen', 'putrajaya-line', 13),
('py14', 'Jalan Ipoh', 'putrajaya-line', 14),
('py15', 'Sentul Barat', 'putrajaya-line', 15),
('py16', 'Titiwangsa', 'putrajaya-line', 16),
('py17', 'Hospital Kuala Lumpur', 'putrajaya-line', 17),
('py18', 'Raja Uda', 'putrajaya-line', 18),
('py19', 'Ampang Park', 'putrajaya-line', 19),
('py20', 'Persiaran KLCC', 'putrajaya-line', 20),
('py21', 'Conlay', 'putrajaya-line', 21),
('py22', 'Tun Razak Exchange', 'putrajaya-line', 22),
('py23', 'Chan Sow Lin', 'putrajaya-line', 23),
('py24', 'Bandar Malaysia Utara', 'putrajaya-line', 24),
('py25', 'Bandar Malaysia Selatan', 'putrajaya-line', 25),
('py26', 'Kuchai', 'putrajaya-line', 26),
('py27', 'Taman Naga Emas', 'putrajaya-line', 27),
('py28', 'Sungai Besi', 'putrajaya-line', 28),
('py29', 'Serdang Raya Utara', 'putrajaya-line', 29),
('py30', 'Serdang Raya Selatan', 'putrajaya-line', 30),
('py31', 'Serdang Jaya', 'putrajaya-line', 31),
('py32', 'UPM', 'putrajaya-line', 32),
('py33', 'Taman Equine', 'putrajaya-line', 33),
('py34', 'Putra Permai', 'putrajaya-line', 34),
('py35', '16 Sierra', 'putrajaya-line', 35),
('py36', 'Cyberjaya Utara', 'putrajaya-line', 36),
('py37', 'Cyberjaya City Centre', 'putrajaya-line', 37),
('py38', 'Putrajaya Sentral', 'putrajaya-line', 38),

-- LRT KELANA JAYA LINE (KJ)
('kj01', 'Gombak', 'kelana-jaya-line', 1),
('kj02', 'Taman Melati', 'kelana-jaya-line', 2),
('kj03', 'Wangsa Maju', 'kelana-jaya-line', 3),
('kj04', 'Sri Rampai', 'kelana-jaya-line', 4),
('kj05', 'Setiawangsa', 'kelana-jaya-line', 5),
('kj06', 'Jelatek', 'kelana-jaya-line', 6),
('kj07', 'Dato Keramat', 'kelana-jaya-line', 7),
('kj08', 'Damai', 'kelana-jaya-line', 8),
('kj09', 'Ampang Park', 'kelana-jaya-line', 9),
('kj10', 'KLCC', 'kelana-jaya-line', 10),
('kj11', 'Kampung Baru', 'kelana-jaya-line', 11),
('kj12', 'Dang Wangi', 'kelana-jaya-line', 12),
('kj13', 'Masjid Jamek', 'kelana-jaya-line', 13),
('kj14', 'Pasar Seni', 'kelana-jaya-line', 14),
('kj15', 'KL Sentral', 'kelana-jaya-line', 15),
('kj16', 'Bangsar', 'kelana-jaya-line', 16),
('kj17', 'Abdullah Hukum', 'kelana-jaya-line', 17),
('kj18', 'Kerinchi', 'kelana-jaya-line', 18),
('kj19', 'Universiti', 'kelana-jaya-line', 19),
('kj20', 'Taman Jaya', 'kelana-jaya-line', 20),
('kj21', 'Asia Jaya', 'kelana-jaya-line', 21),
('kj22', 'Taman Paramount', 'kelana-jaya-line', 22),
('kj23', 'Taman Bahagia', 'kelana-jaya-line', 23),
('kj24', 'Kelana Jaya', 'kelana-jaya-line', 24),
('kj25', 'Lembah Subang', 'kelana-jaya-line', 25),
('kj26', 'Ara Damansara', 'kelana-jaya-line', 26),
('kj27', 'Glenmarie', 'kelana-jaya-line', 27),
('kj28', 'Subang Jaya', 'kelana-jaya-line', 28),
('kj29', 'SS15', 'kelana-jaya-line', 29),
('kj30', 'SS18', 'kelana-jaya-line', 30),
('kj31', 'USJ 7', 'kelana-jaya-line', 31),
('kj32', 'Taipan', 'kelana-jaya-line', 32),
('kj33', 'Wawasan', 'kelana-jaya-line', 33),
('kj34', 'USJ 21', 'kelana-jaya-line', 34),
('kj35', 'Alam Megah', 'kelana-jaya-line', 35),
('kj36', 'Subang Alam', 'kelana-jaya-line', 36),
('kj37', 'Putra Heights', 'kelana-jaya-line', 37),

-- LRT AMPANG LINE (AG)
('ag01', 'Sentul Timur', 'ampang-line', 1),
('ag02', 'Sentul', 'ampang-line', 2),
('ag03', 'Titiwangsa', 'ampang-line', 3),
('ag04', 'PWTC', 'ampang-line', 4),
('ag05', 'Sultan Ismail', 'ampang-line', 5),
('ag06', 'Bandaraya', 'ampang-line', 6),
('ag07', 'Masjid Jamek', 'ampang-line', 7),
('ag08', 'Plaza Rakyat', 'ampang-line', 8),
('ag09', 'Hang Tuah', 'ampang-line', 9),
('ag10', 'Pudu', 'ampang-line', 10),
('ag11', 'Chan Sow Lin', 'ampang-line', 11),
('ag12', 'Miharja', 'ampang-line', 12),
('ag13', 'Maluri', 'ampang-line', 13),
('ag14', 'Pandan Jaya', 'ampang-line', 14),
('ag15', 'Pandan Indah', 'ampang-line', 15),
('ag16', 'Cempaka', 'ampang-line', 16),
('ag17', 'Cahaya', 'ampang-line', 17),
('ag18', 'Ampang', 'ampang-line', 18),

-- LRT SRI PETALING LINE (SP)
('sp01', 'Sentul Timur', 'sri-petaling-line', 1),
('sp02', 'Sentul', 'sri-petaling-line', 2),
('sp03', 'Titiwangsa', 'sri-petaling-line', 3),
('sp04', 'PWTC', 'sri-petaling-line', 4),
('sp05', 'Sultan Ismail', 'sri-petaling-line', 5),
('sp06', 'Bandaraya', 'sri-petaling-line', 6),
('sp07', 'Masjid Jamek', 'sri-petaling-line', 7),
('sp08', 'Plaza Rakyat', 'sri-petaling-line', 8),
('sp09', 'Hang Tuah', 'sri-petaling-line', 9),
('sp10', 'Pudu', 'sri-petaling-line', 10),
('sp11', 'Chan Sow Lin', 'sri-petaling-line', 11),
('sp12', 'Cheras', 'sri-petaling-line', 12),
('sp13', 'Salak Selatan', 'sri-petaling-line', 13),
('sp14', 'Bandar Tun Razak', 'sri-petaling-line', 14),
('sp15', 'Bandar Tasik Selatan', 'sri-petaling-line', 15),
('sp16', 'Sungai Besi', 'sri-petaling-line', 16),
('sp17', 'Bukit Jalil', 'sri-petaling-line', 17),
('sp18', 'Sri Petaling', 'sri-petaling-line', 18),
('sp19', 'Awan Besar', 'sri-petaling-line', 19),
('sp20', 'Muhibbah', 'sri-petaling-line', 20),
('sp21', 'Alam Sutera', 'sri-petaling-line', 21),
('sp22', 'Kinrara BK5', 'sri-petaling-line', 22),
('sp23', 'IOI Puchong Jaya', 'sri-petaling-line', 23),
('sp24', 'Pusat Bandar Puchong', 'sri-petaling-line', 24),
('sp25', 'Taman Perindustrian Puchong', 'sri-petaling-line', 25),
('sp26', 'Bandar Puteri', 'sri-petaling-line', 26),
('sp27', 'Puchong Perdana', 'sri-petaling-line', 27),
('sp28', 'Puchong Prima', 'sri-petaling-line', 28),
('sp29', 'Putra Heights', 'sri-petaling-line', 29),

-- KL MONORAIL (MR)
('mr1', 'KL Sentral', 'kl-monorail', 1),
('mr2', 'Tun Sambanthan', 'kl-monorail', 2),
('mr3', 'Maharajalela', 'kl-monorail', 3),
('mr4', 'Hang Tuah', 'kl-monorail', 4),
('mr5', 'Imbi', 'kl-monorail', 5),
('mr6', 'Bukit Bintang', 'kl-monorail', 6),
('mr7', 'Raja Chulan', 'kl-monorail', 7),
('mr8', 'Bukit Nanas', 'kl-monorail', 8),
('mr9', 'Medan Tuanku', 'kl-monorail', 9),
('mr10', 'Chow Kit', 'kl-monorail', 10),
('mr11', 'Titiwangsa', 'kl-monorail', 11)

ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  line_id = EXCLUDED.line_id,
  sequence = EXCLUDED.sequence;
